name: viornet
description: "ViorNet - WiFi Reseller & ISP Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Database
  drift: ^2.20.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Network & API
  dio: ^5.7.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.0.5
  
  # Authentication & Security
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  crypto: ^3.0.5
  
  # Google Drive Sync
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # SMS (Android)
  telephony: ^0.2.0
  permission_handler: ^11.3.1
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.4.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  
  # File & PDF
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  open_file: ^3.5.7
  excel: ^4.0.6
  
  # Charts & Analytics
  fl_chart: ^0.69.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  
  # UI Components
  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  
  # Device Info
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Date & Time
  jiffy: ^6.3.1
  
  # Responsive
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
